string-value: value
int-value: 1
boolean-value: true

layer: application.yml

array:
  - foo
  - bar

list:
  - foo
  - bar

hash:
  foo: foo
  bar: bar

hashes:
  - foo: foo
    bar: bar
  - foo: foo
    bar: bar

nested-config:
  nested-value: nestedValue

a:
  b:
    c:
      deep-config:
        deep-value: deepValue

random-config:
  value: ${random.value}
  int-value: ${random.int}
  int-value-less-than-ten: ${random.int(10)}
  int-value-in-range: ${random.int[1024,65536]}
  long-value: ${random.long}
  uuid: ${random.uuid}

# If this value is empty, BindException occurs on runtime.
not-empty: notEmpty
